const agents = [
    {
        id: 1,
        name: "John Doe",
        imageUrl: "/p1.jpg",
        about: "Over 10 years in luxury real estate, specializing in high-end properties.",
        phoneNumber: "+1234567890",
        email: "john.doe@example.com",
        experience: "10+ years",
    },
    {
        id: 2,
        name: "Jane Smith",
        imageUrl: "/p2.jpg",
        about: "Architect turned real estate advisor, passionate about sustainable living.",
        phoneNumber: "+1987654321",
        email: "jane.smith@example.com",
        experience: "8 years",
    },
    {
        id: 3,
        name: "Michael Johnson",
        imageUrl: "/p3.jpg",
        about: "Specializes in commercial properties, helping businesses find ideal locations.",
        phoneNumber: "+1122334455",
        email: "michael.johnson@example.com",
        experience: "15 years",
    },
    {
        id: 4,
        name: "Emily Brown",
        imageUrl: "/p4.jpg",
        about: "Helping families find dream homes, committed to client satisfaction.",
        phoneNumber: "+1448877665",
        email: "emily.brown@example.com",
        experience: "7 years",
    },
    {
        id: 5,
        name: "David Wilson",
        imageUrl: "/p5.jpg",
        about: "Real estate investor and advisor, focusing on investment strategies.",
        phoneNumber: "+1555666777",
        email: "david.wilson@example.com",
        experience: "12 years",
    },
    {
        id: 6,
        name: "Sarah Taylor",
        imageUrl: "/p6.jpg",
        about: "Expert in rental property management, dedicated to tenant and owner satisfaction.",
        phoneNumber: "+1666888999",
        email: "sarah.taylor@example.com",
        experience: "9 years",
    },
];

export default agents;