import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from 'react-hot-toast';

import "./globals.css";

const poppins_init = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins_init.className}>
        <Toaster position="top-right" />
        {children}
      </body>
    </html>
  );
}
