import type { Metadata } from "next";
import RootLayout from "./layout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ServerLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <RootLayout>{children}</RootLayout>
        </html>
    );
}